import Head from 'next/head'
import styled from "styled-components"
// Logo
import Logo from '../../public/gummy-location.svg'

export default function Home() {
  return (
    <AppBody>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <AppLogo src={Logo.src} alt="logo" />
        <AppTitle>
          Map<span>Box</span>
        </AppTitle>

        <RoundButton>Get Started</RoundButton>
        <DevCredit>
          Develop by <a href="#">Roger Reyes</a>
        </DevCredit>
      </PageWrapper>
    </AppBody>
  )
}

// Styles AppBody
const AppBody = styled.div`
  position: relative;
  heigth: 100vh;
`;

// Styles Page Wrapper
const PageWrapper = styled.div`
  height: 100%;
  padding: 30px 25px;
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;

  &:before {
    content: "";
    position: absolute;
    background-image: url(Meteor.svg);
    background-size: cover;
    inset: 0;
    opacity: 0,5;
    z-index: -1;
  }
`;

const AppLogo = styled.img`
  max-width: 300px;
`;

const AppTitle = styled.h1`
  margin-top: -40px;
  font-size: 60px;
  font-weight: 700;
  line-height: 90px;
  color: #fff;
  text-transform: uppercase;

  span {
    color: #EE4637;
  }
`;

const RoundButton = styled.button`
  margin: 40px 0;
  padding: 12px 40px;
  background: linear-gradient(0deg, #438ef0, #438ef0),
    linear-gradient(0deg, #279cf1, #279cf1),
    linear-gradient(0deg, #1aa8ef, #1aa8ef),
    linear-gradient(0deg, #2cd3eb, #2cd3eb), #48bde5;
  box-shadow: 6px 6px 12px rgba(0, 0, 0, 0.6);
  border-radius: 50px;
  border: none;
  cursor: pointer;

  font-size: 1rem;
  font-weight: 600;
  line-height: 1.5rem;
  text-transform: uppercase;
  color: #fff;
  transition: 0.3s all;

  &:hover {
    transform: scale(1.1);
  }
`;

const DevCredit = styled.div`
  font-family: Kanit, sans-serif;
  font-size: 1rem;
  line-height: 1rem;
  font-weight: normal;
  color: #fff;

  position: absolute;
  left: 0;
  right: 0;
  bottom: 20px;
  margin: 0 auto;

  a {
    color: #00B0FF;
  }
`;
